### ISSUE TITLE
Uninstall strapi-plugin-comments results in: Error Could not find Custom Field:plugin::comments.comments

### ISSUE THREAD

**Issue by csharpee** [VirtusLab-Open-Source/strapi-plugin-comments#173]
[2022-11-24 13:46:01.600] debug: ⛔️ Server wasn't able to start properly.
[2022-11-24 13:46:01.600] error: Could not find Custom Field: plugin::comments.comments
```
Error: Could not find Custom Field: plugin::comments.comments
    at Object.get (/home/username/nodes/strapi/st-dashboard/node_modules/@strapi/strapi/lib/core/registries/custom-fields.js:34:15)
    at convertCustomFieldType (/home/username/nodes/strapi/st-dashboard/node_modules/@strapi/strapi/lib/utils/convert-custom-field-type.js:15:67)
    at Strapi.register (/home/username/nodes/strapi/st-dashboard/node_modules/@strapi/strapi/lib/Strapi.js:395:5)
    at async Strapi.load (/home/username/nodes/strapi/st-dashboard/node_modules/@strapi/strapi/lib/Strapi.js:474:5)
    at async Strapi.start (/home/username/nodes/strapi/st-dashboard/node_modules/@strapi/strapi/lib/Strapi.js:212:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by csharpee** [comment]
Also, if you have the comments option in the **post** collection, results in white screen on viewing each post. I had to remove the custom fields and restart Strapi. I also defaulted all settings in the plugin.

Then removing the package and building strapi again allowed me to "properly uninstall the plugin".
