### ISSUE TITLE
Warning: comments.app.components.notification.error - similar to closed issue #142

### ISSUE THREAD

**Issue by ursanandrei23** [VirtusLab-Open-Source/strapi-plugin-comments#174]
Hello!

I have an issue, similar to #142. More details can be found in the below images (error from Strapi Dashboard, error from console and the only existing comment) and logs from Strapi. I am using v4.5.3 for Strapi and v2.2.1 for Comments plugin.

<img width="1252" alt="Screenshot 2022-12-06 at 09 14 42" src="https://user-images.githubusercontent.com/115547797/205868542-e534cf93-67db-443c-8517-053cdb4e2d8b.png">

<img width="1076" alt="Screenshot 2022-12-06 at 09 15 18" src="https://user-images.githubusercontent.com/115547797/205868586-8196bdbf-dbd2-4b22-88d7-c7bc09173246.png">

<img width="379" alt="Screenshot 2022-12-06 at 10 05 46" src="https://user-images.githubusercontent.com/115547797/205868621-f75a4004-46a3-43d1-8492-f6f8749bea8f.png">

`[2022-12-06 10:05:29.771] error: Cannot read properties of undefined (reading 'count')
TypeError: Cannot read properties of undefined (reading 'count')
    at pickPopulateParams (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/database/lib/query/helpers/populate/apply.js:602:16)
    at Object.applyPopulate (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/database/lib/query/helpers/populate/apply.js:623:10)
    at Object.execute (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/database/lib/query/query-builder.js:478:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.findMany (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/database/lib/entity-manager/index.js:180:22)
    at async Object.findAll (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/strapi-plugin-comments/server/services/admin.js:97:26)
    at async returnBodyMiddleware (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/Users/andreiursan/work-webmarc/Charger-frontend/app/strapi-blog/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)`

@cyp3rius I've noticed that the old issue was related to avatar field and tried with an actual link, with no avatar and with empty string, nothing worked :( Thanks for the help!!

**Comment by engineers-dope** [comment]
@ursanandrei23 Seems like you're having the same issue with this thread
https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/issues/146

I've added a temp workaround for it, you can try it out it worked for me.

**Comment by cyp3rius** [comment]
@engineers-dope fixed in `v2.2.3`
