### ISSUE TITLE
ModuleNotFoundError when trying to build project

### ISSUE THREAD

**Issue by dstoiko** [VirtusLab-Open-Source/strapi-plugin-comments#196]
## Environment

Here is my local configuration environment:
```
➜  ~ sw_vers
ProductName:		macOS
ProductVersion:		13.1
BuildVersion:		22C65
➜  ~ node --version
v18.14.1
➜  ~ yarn --version
3.4.1
➜  ~ python --version
Python 3.10.9
```

## Issue
When following the [library's docs](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#-installation), I was at the `yarn build` step and I ran into 2 problems, in order of appearance:

1. `ModuleNotFoundError` on missing dependencies for the plugin: it aborts the build process with an error and says "Package required: [missing_package]". Simply adding the missing dependencies to the _package.json_ file is enough, but there are quite a few, and it seems the only way to work around the issue is to `yarn add` the missing package once you find out it's missing, then `yarn build`, and so on until there are no more missing dependencies. So after the 3rd missing dependency, I got lazy and wrote a python script to automate this (if there's a better way to do this I'm all ears). I put a reference to this script at the bottom of the issue for anyone interested.

FYI, here is the list of missing dependencies I got:
```
sanitize-html
highlight.js
markdown-it
markdown-it-abbr
markdown-it-container
markdown-it-deflist
markdown-it-emoji
markdown-it-footnote
markdown-it-ins
markdown-it-mark
markdown-it-sub
markdown-it-sup
```

2. Another `ModuleNotFoundError` but I'm unable to solve this one: `Can't resolve 'highlight.js/styles/solarized-dark.css'`. Because I already installed highlight.js, I cannot go past this step. Apparently, it comes from [this piece of code in your library](https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/blob/master/admin/src/components/PreviewWysiwyg/utils/mdRenderer.ts#L23):
```js
const loadCss = async () => {
  await import(/* webpackChunkName: "highlight.js" */ 'highlight.js/styles/solarized-dark.css');
};
```
In the highlight.js library, the _solarized-dark.css_ file is under the [styles/base16](https://github.com/highlightjs/highlight.js/tree/main/src/styles/base16) folder. Maybe I need to downgrade to an older version of highlight.js for it to work?

NB: the python script I mentioned in 1.:
```py
import subprocess
import re

def install_missing():
    pkgs = []
    while True:
        # Find package name in error
        res = subprocess.run(["yarn", "build"], capture_output=True)
        if len(res.stderr) == 0:
            break
        m = re.search("Required package: ([a-zA-Z0-9\-\.@\/]+)", res.stderr.decode("utf-8"))
        if m is None:
            break
        pkg = m.group(1)
        print(f'Found missing package {pkg}')
        pkgs.append(pkg)
        # Install missing package
        res = subprocess.run(["yarn", "add", pkg], capture_output=True)
        if len(res.stderr) > 0:
            print(res.stderr.decode("utf-8"))
            break
        m = re.search("Done", res.stdout.decode("utf-8"))
        if m is None:
            print(res.stdout.decode("utf-8"))
            break
        print(f'Installed package {pkg}')

    # Print package names line by line
    for p in pkgs:
        print(p)

if __name__ == "__main__":
    install_missing()
````
```

**Comment by everythinginjs** [comment]
1+
same issue
env:
node: v16.19.1
strapi: v4.4.3

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/icons/dist'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve 'react/jsx-runtime' in '/Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/icons/dist'
  Parsed request is a module
  using description file: /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/icons/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/icons/dist/node_modules doesn't exist or is not a directory
      /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/icons/node_modules doesn't exist or is not a directory
      /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/node_modules doesn't exist or is not a directory
      /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules
        existing directory /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/react
          using description file: /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/react/package.json (relative path: .)
            using description file: /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/react/package.json (relative path: ./jsx-runtime)
              Field 'browser' doesn't contain a valid alias configuration
              /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/react/jsx-runtime doesn't exist
      looking for modules in /Users/amirmahmoodi/Desktop/shahdarad/node_modules
        /Users/amirmahmoodi/Desktop/shahdarad/node_modules/react doesn't exist
      looking for modules in /Users/amirmahmoodi/Desktop/node_modules
        /Users/amirmahmoodi/Desktop/node_modules/react doesn't exist
      looking for modules in /Users/amirmahmoodi/node_modules
        /Users/amirmahmoodi/node_modules/react doesn't exist
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/admin/node_modules
        /Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/admin/node_modules/react doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'react/jsx-runtime' in '/Users/amirmahmoodi/Desktop/shahdarad/backend/node_modules/@strapi/icons/dist'
```

**Comment by everythinginjs** [comment]
I found a similar issue on strapi repo [here](https://github.com/strapi/strapi/issues/11945)
