### ISSUE TITLE
Invalid Record Length

### ISSUE THREAD

**Issue by Jahorse** [VirtusLab-Open-Source/strapi-plugin-comments#234]
I'm seeing the following error on my Strapi server from time to time when trying to access comments. I don't really have any ideas on how to begin debugging it:

```
Error: Invalid Record Length: columns length is 28, got 1 on line 1
    at Object.__onRecord (/mnt/http/backend/node_modules/csv-parse/dist/cjs/index.cjs:958:11)
    at Object.parse (/mnt/http/backend/node_modules/csv-parse/dist/cjs/index.cjs:913:36)
    at Parser._flush (/mnt/http/backend/node_modules/csv-parse/dist/cjs/index.cjs:1347:26)
    at Parser.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at Writable.end (node:internal/streams/writable:634:5)
    at Immediate.writer [as _onImmediate] (/mnt/http/backend/node_modules/csv-parse/dist/cjs/index.cjs:1398:14)
    at process.processImmediate (node:internal/timers:476:21)
```

**Comment by Jahorse** [comment]
I now believe this is unrelated to the comments plugin
